# Configs for model
model_type: BaseModel
model_configs:
  vocab_size: 10000
  embedding_dim: 64
  hidden_dim: 256
  num_layers: 4
  num_classes: 2

# Configs for data
data_loader_path: "sample.dill"

# Configs for training
epoch: 10
batch_size: 64
val_batch_size: 512
learning_rate: 1.e-4
optimizer: "SGD"
steps_per_log: 100
steps_per_eval: 1000

model_save_dir: "."
model_save_prefix: "models"

optimizer_args: 
  momentum: 0.9
